# -*- coding: utf-8 -*-
"""Copy of partial_face_modified.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E7BVIRXXYZxX5zq-RsQOw8PNmhD65qtR
"""

import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import load_model
from google.colab import drive

drive.mount('/content/drive')

!nvidia-smi

# Define base paths
base_path = "/content/drive/MyDrive/face_recognition"
faces_path = os.path.join(base_path, "Faces")  # Direct images
original_images_path = os.path.join(base_path, "Original Images")

csv_path = os.path.join(base_path, "/content/drive/MyDrive/face_recognition/Dataset.csv")
df = pd.read_csv(csv_path)

import os
import pandas as pd


# Create full path for each image
df["full_path"] = df.apply(lambda row: os.path.join(original_images_path, row["label"], row["id"]), axis=1)

# Check if paths exist
for path in df["full_path"].head(10):  # Test first 10 rows
    print(f"🔍 Checking: {path} → Exists: {os.path.exists(path)}")

df = pd.read_csv(csv_path)
print("Dataset Sample:\n", df.head())

# 📌 Image Preprocessing Function
def preprocess_image(image_path, img_size=(128, 128)):
    image = cv2.imread(image_path)
    image = cv2.resize(image, img_size)  # Resize image
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # Convert BGR to RGB
    image = image / 255.0  # Normalize
    return image

images, labels = [], []

for index, row in df.iterrows():
    img_path = os.path.join(original_images_path, row["label"], row["id"])  # Construct correct path

    if os.path.exists(img_path):
        img = preprocess_image(img_path)
        images.append(img)
        labels.append(row["label"])
    else:
        print(f"❌ Image not found: {img_path}")

print(f"✅ Loaded {len(images)} images successfully!")

!ls "/content/drive/MyDrive/face_recognition/Original Images/Alia Bhatt/"

images = np.array(images)
labels = np.array(labels)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
labels = le.fit_transform(labels)  # Convert names to numbers

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)),
    MaxPooling2D(2, 2),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(len(le.classes_), activation='softmax')  # Output layer with classes
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")

test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"✅ Model Accuracy: {test_acc*100:.2f}%")

import tensorflow as tf
tf.keras.backend.clear_session()

# Check TensorFlow version
print(tf.__version__)

import numpy as np

print(f"X_train type: {type(X_train)}, shape: {X_train.shape if isinstance(X_train, np.ndarray) else 'N/A'}")
print(f"y_train type: {type(y_train)}, shape: {y_train.shape if isinstance(y_train, np.ndarray) else 'N/A'}")

# Check for NaN values
print(f"Any NaN in X_train? {np.isnan(X_train).sum()}")
print(f"Any NaN in y_train? {np.isnan(y_train).sum()}")

# Print first sample
print(f"First label: {y_train[0] if len(y_train) > 0 else 'No Data'}")

from tensorflow.keras.utils import to_categorical

num_classes = len(set(y_train))  # Unique classes
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

print(f"y_train shape after encoding: {y_train.shape}")

X_train = np.array(X_train, dtype=np.float32) / 255.0
X_test = np.array(X_test, dtype=np.float32) / 255.0

try:
    model.summary()
except Exception as e:
    print(f"❌ Model not found: {e}")

model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

y_train = np.argmax(y_train, axis=1)  # Convert from one-hot to integers
y_test = np.argmax(y_test, axis=1)

model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

# 📌 Function to Predict Faces
def predict_face(image_path):
    img = preprocess_image(image_path)
    img = np.expand_dims(img, axis=0)  # Add batch dimension
    prediction = model.predict(img)
    predicted_label = np.argmax(prediction)
    person_name = le.inverse_transform([predicted_label])[0]

    # 📌 Display Image
    img_display = cv2.imread(image_path)
    img_display = cv2.cvtColor(img_display, cv2.COLOR_BGR2RGB)

    plt.imshow(img_display)
    plt.title(f"Predicted: {person_name}")
    plt.axis("off")
    plt.show()

!pip install keras_facenet

from keras_facenet import FaceNet
import numpy as np
import os
import cv2
from scipy.spatial.distance import cosine

# Load Pretrained FaceNet Model
embedder = FaceNet()
print("✅ FaceNet model loaded successfully!")

dataset_path = "/content/drive/MyDrive/face_recognition/Original Images"  # Update with your dataset path
face_db = {}

# Function to Extract Face Embeddings
def get_embedding(image_path):
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (160, 160))  # FaceNet requires 160x160 images
    image = np.expand_dims(image, axis=0)
    embedding = embedder.embeddings(image)
    return embedding[0]  # 128D feature vector

# Extract embeddings for all images
for person in os.listdir(dataset_path):
    person_path = os.path.join(dataset_path, person)
    if os.path.isdir(person_path):
        for image in os.listdir(person_path):
            img_path = os.path.join(person_path, image)
            face_db[img_path] = get_embedding(img_path)

print(f"✅ Stored {len(face_db)} face embeddings.")

def recognize_face(test_img_path):
    test_embedding = get_embedding(test_img_path)
    min_distance = float("inf")
    best_match = None

    for img_path, emb in face_db.items():
        distance = cosine(test_embedding, emb)  # Cosine similarity
        if distance < min_distance:
            min_distance = distance
            best_match = img_path

    print(f"✅ Closest match: {best_match} (Cosine Distance: {min_distance:.4f})")

# Test on a new face
test_image = "/content/Amitabh Bacchan.jpg"  # Change this to your test image path
recognize_face(test_image)

import cv2
import numpy as np
import matplotlib.pyplot as plt

def show_prediction(test_image_path, model, face_db):
    # Load the test image
    test_image = cv2.imread(test_image_path)
    if test_image is None:
        print("❌ Image could not be loaded. Check the file path.")
        return

    test_image_rgb = cv2.cvtColor(test_image, cv2.COLOR_BGR2RGB)
    test_image_resized = cv2.resize(test_image_rgb, (160, 160))
    test_image_resized = np.expand_dims(test_image_resized, axis=0)

    # Get embedding
    test_embedding = model.embeddings(test_image_resized)

    # Find closest match
    min_dist = float("inf")
    best_match = None
    best_match_image = None

    for img_path, stored_embedding in face_db.items():
        dist = np.linalg.norm(test_embedding - stored_embedding)
        if dist < min_dist:
            min_dist = dist
            best_match = img_path
            best_match_image = cv2.imread(best_match)

    if best_match_image is None:
        print("❌ No match found.")
        return

    best_match_image_rgb = cv2.cvtColor(best_match_image, cv2.COLOR_BGR2RGB)

    # Show images
    fig, axes = plt.subplots(1, 2, figsize=(10, 5))

    axes[0].imshow(test_image_rgb)
    axes[0].set_title("Input Image")
    axes[0].axis("off")

    axes[1].imshow(best_match_image_rgb)
    axes[1].set_title(f"Recognized as: {best_match.split('/')[-2]}")
    axes[1].axis("off")

    plt.show()

test_image_path = "/content/Amitabh Bacchan.jpg"  # Change this
show_prediction(test_image_path, embedder, face_db)

!pip install deepface

from deepface import DeepFace

# Input image
image_path = "/content/drive/MyDrive/face_recognition/Faces/Alexandra Daddario_54.jpg"

# Perform Face Recognition + Emotion Analysis
results = DeepFace.analyze(img_path=image_path, actions=["emotion"], detector_backend="opencv", enforce_detection=False)  # Set enforce_detection to False

# Print results
print("Emotion Analysis:", results[0]["dominant_emotion"])

pip install opencv-python tensorflow numpy imutils

"""in this code we are getting some suspect person from cctv live feed"""

import cv2
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.preprocessing.image import img_to_array
import imutils

# Load the pre-trained Partial Face Recognition model
model = load_model("partial_face_model.h5")
# Ensure you have this trained model

# Load MobileNetV2 for feature extraction
mobilenet = MobileNetV2(weights="imagenet", include_top=False, input_shape=(128, 128, 3))

# Load Haar cascade for face detection
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")

# Connect to CCTV (Replace URL with your CCTV RTSP/HTTP stream or use 0 for webcam)
cctv_url = "rtsp://username:password@cctv_ip:port/stream"
cap = cv2.VideoCapture(cctv_url)

# Function to preprocess image for MobileNetV2
def preprocess_face(face):
    face = cv2.resize(face, (224, 224))
    face = img_to_array(face)
    face = np.expand_dims(face, axis=0)
    face = face / 255.0  # Normalize
    return face

# Real-time CCTV Partial Face Recognition
while True:
    ret, frame = cap.read()
    if not ret:
        print("Failed to grab frame. Check CCTV stream.")
        break

    frame = imutils.resize(frame, width=800)
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(60, 60))

    for (x, y, w, h) in faces:
        face_roi = frame[y:y+h, x:x+w]
        processed_face = preprocess_face(face_roi)

        # Extract features using MobileNetV2
        features = mobilenet.predict(processed_face)
        features = features.reshape(1, -1)  # Flatten for LSTM input

        # Predict identity
        prediction = model.predict(features)
        label = "Unknown"
        confidence = np.max(prediction) * 100

        # Assign label based on confidence threshold
        if confidence > 80:
            label = f"Person {np.argmax(prediction)}"

        # Draw bounding box and label
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(frame, f"{label}: {confidence:.2f}%", (x, y - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

    # Display CCTV feed with recognition
    cv2.imshow("CCTV Partial Face Recognition", frame)

    if cv2.waitKey(1) & 0xFF == ord("q"):  # Press 'q' to quit
        break

cap.release()
cv2.destroyAllWindows()